name: Project Actions

on: workflow_dispatch
jobs:
    CICD:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              
            - name: Maven test
              run: mvn test

            - name: Checkstyle
              run: mvn checkstyle:checkstyle
            
            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '11'
            - name: Setup SonarQube
              uses: warchant/setup-sonar-scanner@v7
              
            - name: SonarQube Scanner
              run: sonar-scanner
               -Dsonar.host.url=${{ secrets.SONAR_URL }}
               -Dsonar.login=${{ secrets.SONAR_TOKEN }}
               -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
               -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
             
               -Dsonar.sources=src/
               -Dsonar.junit.reportsPath=target/surefire-reports/ 
               -Dsonar.jacoco.reportsPath=target/jacoco.exec 
               -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
               -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/
                   




