name: Project Actions

on: workflow_dispatch
jobs:
    CICD:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              
            - name: Maven test
              run: mvm test
              
            - name: Checkstyle
              run: checkstyle:checkstyle    

